services:
  - type: web
    name: rails-render-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: bundle exec rake assets:precompile
    startCommand: bundle exec rails db:migrate RAILS_ENV=production && bundle exec rails s -b 0.0.0.0 -p $PORT


